insert into artists(artist_name) values('Fulviet');
            insert into artists(artist_name) values('MUZAI');
            insert into artists(artist_name) values('Carolina Caldeira');
            insert into artists(artist_name) values('Color Blind Colective');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('Vanessa Teodoro');
            insert into artists(artist_name) values('FLIX');
            insert into artists(artist_name) values('TVFER');
            insert into artists(artist_name) values('João Samina');
            insert into artists(artist_name) values('GLAM');
            insert into artists(artist_name) values('Mozaik');
            insert into artists(artist_name) values('Mynameisnotsem');
            insert into artists(artist_name) values('Peeta');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('NSN 997');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('STRA');
            insert into artists(artist_name) values('Regg');
            insert into artists(artist_name) values('Third');
            insert into artists(artist_name) values('2CARRYON');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('SAUB');
            insert into artists(artist_name) values('SOSEK');
            insert into artists(artist_name) values('Blac Dwelle');
            insert into artists(artist_name) values('Maria Imaginário');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Mariana PTKS');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Helio Bray');
            insert into artists(artist_name) values('Mozaik');
            insert into artists(artist_name) values('THIAGO NEVS');
            insert into artists(artist_name) values('Colectivo Rua');
            insert into artists(artist_name) values('Coxas');
            insert into artists(artist_name) values('Ana Aragão');
            insert into artists(artist_name) values('Sara Morais');
            insert into artists(artist_name) values('Thunders Crew');
            insert into artists(artist_name) values('SUBTU');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Colectivo MUDA');
            insert into artists(artist_name) values('Reveracidade');
            insert into artists(artist_name) values('Otto Schade');
            insert into artists(artist_name) values('Omik');
            insert into artists(artist_name) values('Helio Bray');
            insert into artists(artist_name) values('Choy Two');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Gustavo Baseggio');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('aFase');
            insert into artists(artist_name) values('Aldam Street Art');
            insert into artists(artist_name) values('Vanessa Teodoro');
            insert into artists(artist_name) values('OSIR');
            insert into artists(artist_name) values('Aldam Street Art');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('John Beijer');
            insert into artists(artist_name) values('Gustavo Baseggio');
            insert into artists(artist_name) values('SUBTU');
            insert into artists(artist_name) values('BOZIK');
            insert into artists(artist_name) values('AKUE');
            insert into artists(artist_name) values('DADDYSTREETFOX');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('IAMSOMEART');
            insert into artists(artist_name) values('MISTER P');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('MISTER P');
            insert into artists(artist_name) values('Wasted Rita');
            insert into artists(artist_name) values('Quê?');
            insert into artists(artist_name) values('BELLAPHAME');
            insert into artists(artist_name) values('COVCO');
            insert into artists(artist_name) values('Risko');
            insert into artists(artist_name) values('ROUND1CREW');
            insert into artists(artist_name) values('MIDNIGHT MADNESS CREW');
            insert into artists(artist_name) values('KOER');
            insert into artists(artist_name) values('TIMER');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('NUREA');
            insert into artists(artist_name) values('MONSTER');
            insert into artists(artist_name) values('ALEX SENNA');
            insert into artists(artist_name) values('GLAM');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('Quê?');
            insert into artists(artist_name) values('Hium');
            insert into artists(artist_name) values('2UPLA');
            insert into artists(artist_name) values('PREGOS SHP');
            insert into artists(artist_name) values('Tony Tuan Loung');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('REZENDE');
            insert into artists(artist_name) values('JOTAPE PAX');
            insert into artists(artist_name) values('Pso Man');
            insert into artists(artist_name) values('WERENS');
            insert into artists(artist_name) values('DISHDISH');
            insert into artists(artist_name) values('PR0L233');
            insert into artists(artist_name) values('EHME');
            insert into artists(artist_name) values('Erb Mon');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('DISHDISH');
            insert into artists(artist_name) values('EHME');
            insert into artists(artist_name) values('Margarida Fleming');
            insert into artists(artist_name) values('FLIX');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Gregos Art');
            insert into artists(artist_name) values('Ludovic Olivo');
            insert into artists(artist_name) values('Gregos Art');
            insert into artists(artist_name) values('Mister Piro');
            insert into artists(artist_name) values('Hayley Welsh');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Leo Lunatic');
            insert into artists(artist_name) values('Noty Aroz');
            insert into artists(artist_name) values('Neon Savage');
            insert into artists(artist_name) values('Derlon');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Mito');
            insert into artists(artist_name) values('GRUPO OPNI');
            insert into artists(artist_name) values('Tombo');
            insert into artists(artist_name) values('Tombo');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Labrona');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Labrona');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Ecloz');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Vile Graffiti');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('SprayLover');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('APE');
            insert into artists(artist_name) values('Paula Marie Art');
            insert into artists(artist_name) values('Alice Dolling Art');
            insert into artists(artist_name) values('Pitanga');
            insert into artists(artist_name) values('ANDRÉ ACER');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Mojojojo');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Tiago Hacke');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Webix Art');
            insert into artists(artist_name) values('Sept');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Pintamonos');
            insert into artists(artist_name) values('Fulviet');
            insert into artists(artist_name) values('Mist Graffist');
            insert into artists(artist_name) values('Crazy Mister Sketch');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Tijanatri');
            insert into artists(artist_name) values('Sticker Maid Berlin');
            insert into artists(artist_name) values('Sticker Maid Berlin');
            insert into artists(artist_name) values('Sticker Maid Berlin');
            insert into artists(artist_name) values('André Carrilho');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('EreiraCity');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('Reveracidade');
            insert into artists(artist_name) values('Rajni');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Rajni');
            insert into artists(artist_name) values('Afrogame');
            insert into artists(artist_name) values('GARGAMELI WILDTIGER');
            insert into artists(artist_name) values('Rosalette');
            insert into artists(artist_name) values('Assis Raoni');
            insert into artists(artist_name) values('GARGAMELI WILDTIGER');
            insert into artists(artist_name) values('Adres');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('TheWalters');
            insert into artists(artist_name) values('TheWalters');
            insert into artists(artist_name) values('TheWalters');
            insert into artists(artist_name) values('FIXESM');
            insert into artists(artist_name) values('TheWalters');
            insert into artists(artist_name) values('FIXESM');
            insert into artists(artist_name) values('BSRIS');
            insert into artists(artist_name) values('TBLR ONE');
            insert into artists(artist_name) values('NELIO');
            insert into artists(artist_name) values('NELIO');
            insert into artists(artist_name) values('NELIO');
            insert into artists(artist_name) values('NELIO');
            insert into artists(artist_name) values('Mornan');
            insert into artists(artist_name) values('ACAB');
            insert into artists(artist_name) values('Thoma Vuille');
            insert into artists(artist_name) values('INSA');
            insert into artists(artist_name) values('M. Chat');
            insert into artists(artist_name) values('DOLK');
            insert into artists(artist_name) values('Agência Ivity');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('SKIR');
            insert into artists(artist_name) values('Binau');
            insert into artists(artist_name) values('Noir');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Low Bros');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Paulo Arraiano');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Mário Belém');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Miguel Ayako');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Nark');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('Miguel Januário');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('João Samina');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Pedro Batista');
            insert into artists(artist_name) values('Fidel Évora');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('Mariana Dias Coutinho');
            insert into artists(artist_name) values('Drawing Jesus');
            insert into artists(artist_name) values('Sphiza');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('±maismenos±');
            insert into artists(artist_name) values('Maria Imaginário');
            insert into artists(artist_name) values('Ephy');
            insert into artists(artist_name) values('Maria Imaginário');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('GLAM');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('PixelPancho');
            insert into artists(artist_name) values('How and Nosm');
            insert into artists(artist_name) values('Vanessa Teodoro');
            insert into artists(artist_name) values('Interesni Kazki');
            insert into artists(artist_name) values('How and Nosm');
            insert into artists(artist_name) values('Wasted Rita');
            insert into artists(artist_name) values('João Samina');
            insert into artists(artist_name) values('Fábio Colaço');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('António Luengo');
            insert into artists(artist_name) values('Paulo Arraiano');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Chure Oner');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Marcelo Dantas');
            insert into artists(artist_name) values('João Samina');
            insert into artists(artist_name) values('Nicolae Negura');
            insert into artists(artist_name) values('Drawing Jesus');
            insert into artists(artist_name) values('DRAW');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Cyrcle');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Cyrcle');
            insert into artists(artist_name) values('PixelPancho');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('Filipe Matias');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('Lucy McLauchlan');
            insert into artists(artist_name) values('Brad Downey');
            insert into artists(artist_name) values('Momo');
            insert into artists(artist_name) values('EricaIlCane');
            insert into artists(artist_name) values('Bastardilla');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('Remed');
            insert into artists(artist_name) values('sam3');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Os Gémeos');
            insert into artists(artist_name) values('Boris Oppek');
            insert into artists(artist_name) values('Paulo Arraiano');
            insert into artists(artist_name) values('Leonor Morais');
            insert into artists(artist_name) values('Akay');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Travis');
            insert into artists(artist_name) values('Sue &amp; Harpo');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('Vitor Santos');
            insert into artists(artist_name) values('Maria Imaginário');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('GLAM');
            insert into artists(artist_name) values('Nuria');
            insert into artists(artist_name) values('Kebekua');
            insert into artists(artist_name) values('Dalaiama');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Stu');
            insert into artists(artist_name) values('MONSTER');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('Recan');
            insert into artists(artist_name) values('Chure Oner');
            insert into artists(artist_name) values('Cristina Novo');
            insert into artists(artist_name) values('Nina Pontes');
            insert into artists(artist_name) values('Manuel Vilas');
            insert into artists(artist_name) values('Ricardo Metrogos');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Opeo');
            insert into artists(artist_name) values('UBER');
            insert into artists(artist_name) values('HOULS');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('UBER');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('FATE');
            insert into artists(artist_name) values('WISE (NOMEN)');
            insert into artists(artist_name) values('OMO');
            insert into artists(artist_name) values('Youth One');
            insert into artists(artist_name) values('Creyz');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('MES');
            insert into artists(artist_name) values('UDP');
            insert into artists(artist_name) values('O grito do povo');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('UDP');
            insert into artists(artist_name) values('PCP (R)');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('UDP');
            insert into artists(artist_name) values('PS');
            insert into artists(artist_name) values('APU');
            insert into artists(artist_name) values('PCP (R)');
            insert into artists(artist_name) values('APU');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('PPD/PSD');
            insert into artists(artist_name) values('PPD/PSD');
            insert into artists(artist_name) values('UDP/PSR');
            insert into artists(artist_name) values('LST');
            insert into artists(artist_name) values('PPM');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('APU');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('PCP');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('UDP/PSR');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Violant');
            insert into artists(artist_name) values('Drawing Jesus');
            insert into artists(artist_name) values('Nunca');
            insert into artists(artist_name) values('Okuda');
            insert into artists(artist_name) values('Sainer');
            insert into artists(artist_name) values('Clemens Behr');
            insert into artists(artist_name) values('Violant');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Finok');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('Robert Panda');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('Low Bros');
            insert into artists(artist_name) values('Low Bros');
            insert into artists(artist_name) values('Low Bros');
            insert into artists(artist_name) values('Felipe Pantone');
            insert into artists(artist_name) values('Mathieu Tremblin');
            insert into artists(artist_name) values('±maismenos±');
            insert into artists(artist_name) values('Violant');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('UBER');
            insert into artists(artist_name) values('Adres');
            insert into artists(artist_name) values('Adres');
            insert into artists(artist_name) values('J. Aracê');
            insert into artists(artist_name) values('Adres');
            insert into artists(artist_name) values('Lata 65');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Vitó');
            insert into artists(artist_name) values('Mr Dheo');
            insert into artists(artist_name) values('The Caver');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Borondo');
            insert into artists(artist_name) values('Isa Silva');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Borondo');
            insert into artists(artist_name) values('Mário Belém');
            insert into artists(artist_name) values('Regg');
            insert into artists(artist_name) values('Colectivo Rua');
            insert into artists(artist_name) values('Jhon Douglas');
            insert into artists(artist_name) values('Vanessa Rosa');
            insert into artists(artist_name) values('Alexandre Alonso');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('The Super Van');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Mocs. Lois');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('SPOK');
            insert into artists(artist_name) values('André da Loba');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('The Super Van');
            insert into artists(artist_name) values('The Empty Belly');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('Le Zoo');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Remed');
            insert into artists(artist_name) values('Samina');
            insert into artists(artist_name) values('Pout');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('Semor');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Mojojojo');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Aitch');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Van Ayres');
            insert into artists(artist_name) values('Capitain Lusitania');
            insert into artists(artist_name) values('Isabel da Graça');
            insert into artists(artist_name) values('Dub');
            insert into artists(artist_name) values('Mata*H4ri');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Granje');
            insert into artists(artist_name) values('Drawing Jesus');
            insert into artists(artist_name) values('APAURB');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('Mignor');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('PCTP-MRPP');
            insert into artists(artist_name) values('Grud');
            insert into artists(artist_name) values('Hugo Makarov');
            insert into artists(artist_name) values('Carlos Farinha');
            insert into artists(artist_name) values('Telmo Alcobia');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('±maismenos±');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Regg');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Paulo Arraiano');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Miguel Januário');
            insert into artists(artist_name) values('INTI');
            insert into artists(artist_name) values('Bicicleta Sem Freio');
            insert into artists(artist_name) values('Mariana Dias Coutinho');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Julian');
            insert into artists(artist_name) values('Alpinistas Descalços');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('SPEK');
            insert into artists(artist_name) values('Francisco Ponto');
            insert into artists(artist_name) values('MAAT');
            insert into artists(artist_name) values('Francisco Camilo');
            insert into artists(artist_name) values('Trafic');
            insert into artists(artist_name) values('Gustavo São Pedro');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Francisco Correia');
            insert into artists(artist_name) values('Margarida Esteves');
            insert into artists(artist_name) values('Nicolae Negura');
            insert into artists(artist_name) values('Vanessa Teodoro');
            insert into artists(artist_name) values('Drawing Jesus');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Robert Panda');
            insert into artists(artist_name) values('Grud');
            insert into artists(artist_name) values('David Leitner');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Mojojojo');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Guilherme Filipe');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Alexandra Bodianu');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Ricardo Xavier Antunes');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Tim Etchells');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Godmess');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Andre');
            insert into artists(artist_name) values('Hagaiel');
            insert into artists(artist_name) values('Margarida Esteves');
            insert into artists(artist_name) values('Sofia Pidwell');
            insert into artists(artist_name) values('Isa Silva');
            insert into artists(artist_name) values('Cane Morto');
            insert into artists(artist_name) values('Rede 8 de Março');
            insert into artists(artist_name) values('Alice Pasquini');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Jorit');
            insert into artists(artist_name) values('Vanessa Teodoro');
            insert into artists(artist_name) values('Godmess');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Ricardo Guerreiro');
            insert into artists(artist_name) values('Nadine Boulengier');
            insert into artists(artist_name) values('Cane Morto');
            insert into artists(artist_name) values('Vanessa Rosa');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Rafael Silva');
            insert into artists(artist_name) values('Pedro Laureano Diniz');
            insert into artists(artist_name) values('Zana Moraes');
            insert into artists(artist_name) values('Célia Ribeiro');
            insert into artists(artist_name) values('Crianças do Infantário Popular Ribeiro dos Santos');
            insert into artists(artist_name) values('Miguel Nozolino');
            insert into artists(artist_name) values('Illegals');
            insert into artists(artist_name) values('2Hands');
            insert into artists(artist_name) values('RiqRak');
            insert into artists(artist_name) values('António Garcia');
            insert into artists(artist_name) values('Cláudio Martins');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Nina Pontes');
            insert into artists(artist_name) values('Renato Lopes');
            insert into artists(artist_name) values('AFeel');
            insert into artists(artist_name) values('LaClew');
            insert into artists(artist_name) values('LaClew');
            insert into artists(artist_name) values('Bernardo Grade Coelho');
            insert into artists(artist_name) values('LaClew');
            insert into artists(artist_name) values('Pedro Diniz');
            insert into artists(artist_name) values('Ivo Samuel');
            insert into artists(artist_name) values('Dynker');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('Maria Inês Andrade');
            insert into artists(artist_name) values('Miguel Januário');
            insert into artists(artist_name) values('Tosco');
            insert into artists(artist_name) values('Hium');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Rita Máximo Pestana');
            insert into artists(artist_name) values('Escuteiros da Penha de França');
            insert into artists(artist_name) values('Ricardo Xavier Antunes');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Emanuel Lopes');
            insert into artists(artist_name) values('João Pequito');
            insert into artists(artist_name) values('Myster');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Crianças do Infantário Popular Ribeiro dos Santos');
            insert into artists(artist_name) values('Nark');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Rote');
            insert into artists(artist_name) values('FYA');
            insert into artists(artist_name) values('Rui Fernando Carvalho Pinto');
            insert into artists(artist_name) values('Marta Nunes');
            insert into artists(artist_name) values('B. Shanti');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('Rafi');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('Les Gens');
            insert into artists(artist_name) values('Kj263');
            insert into artists(artist_name) values('Quê?');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('To/Let');
            insert into artists(artist_name) values('Zana Moraes');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Richard Câmara');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Obey (PT)');
            insert into artists(artist_name) values('C215');
            insert into artists(artist_name) values('Nuno Coelho');
            insert into artists(artist_name) values('Hugo Henriques');
            insert into artists(artist_name) values('The Bows');
            insert into artists(artist_name) values('Hium');
            insert into artists(artist_name) values('Atsok');
            insert into artists(artist_name) values('Quê?');
            insert into artists(artist_name) values('Risko');
            insert into artists(artist_name) values('Mister');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('Rede 8 de Março');
            insert into artists(artist_name) values('Uivo');
            insert into artists(artist_name) values('Jimmy C');
            insert into artists(artist_name) values('Ôje');
            insert into artists(artist_name) values('Isa Silva');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('Cláudio Filipe Amaral Martins');
            insert into artists(artist_name) values('Cláudio Filipe Amaral Martins');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Cláudio Filipe Amaral Martins');
            insert into artists(artist_name) values('Ana Dominguez');
            insert into artists(artist_name) values('Francisco Correia');
            insert into artists(artist_name) values('Joana Motta Guedes');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Granje');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('Zacharevic');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('The Super Van');
            insert into artists(artist_name) values('Myneandyours');
            insert into artists(artist_name) values('Andrea Tarli');
            insert into artists(artist_name) values('Pariz One');
            insert into artists(artist_name) values('Edis One');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Cane Morto');
            insert into artists(artist_name) values('HNRX');
            insert into artists(artist_name) values('AFID');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Brandia Central');
            insert into artists(artist_name) values('Leonor Brilha');
            insert into artists(artist_name) values('Mariana Dias Coutinho');
            insert into artists(artist_name) values('Godmess');
            insert into artists(artist_name) values('EBANOCollective');
            insert into artists(artist_name) values('Novecinco');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('JR');
            insert into artists(artist_name) values('Koctel');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Nicolae Negura');
            insert into artists(artist_name) values('Olivier Kosta-Théfaine');
            insert into artists(artist_name) values('Fernando José Lobo Rodrigues');
            insert into artists(artist_name) values('Vera Martins');
            insert into artists(artist_name) values('Maura Faria');
            insert into artists(artist_name) values('APAURB');
            insert into artists(artist_name) values('Samir Patel Rebelo');
            insert into artists(artist_name) values('Loco Motiv');
            insert into artists(artist_name) values('Pariz One');
            insert into artists(artist_name) values('Agência Calipo');
            insert into artists(artist_name) values('Aka Corleone');
            insert into artists(artist_name) values('Rui Alexandre Fortes Marques Ferreira');
            insert into artists(artist_name) values('Samantha Rego de Almeida');
            insert into artists(artist_name) values('Emanuel Rosa');
            insert into artists(artist_name) values('APAURB');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Isa Silva');
            insert into artists(artist_name) values('COLECTIVO UNIGATOR - Sérgio Miguel Sequeira');
            insert into artists(artist_name) values('Pedro Daniel Diniz da Silva Pereira');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Robô');
            insert into artists(artist_name) values('Hugo Henriques');
            insert into artists(artist_name) values('Nicolae Negura');
            insert into artists(artist_name) values('Hugo Henriques');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Nicolae Negura');
            insert into artists(artist_name) values('Black Panters');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Oneart Crew');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('União Artística do Trancão');
            insert into artists(artist_name) values('Sega');
            insert into artists(artist_name) values('Nark');
            insert into artists(artist_name) values('Laser');
            insert into artists(artist_name) values('Faif');
            insert into artists(artist_name) values('Creyz');
            insert into artists(artist_name) values('Nelson Ferreira');
            insert into artists(artist_name) values('Marcos Granja');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Creyz');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Quê?');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Creyz');
            insert into artists(artist_name) values('Peras');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Pso Man');
            insert into artists(artist_name) values('Lois');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Pso Man');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('HNRX');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Sega');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Lois');
            insert into artists(artist_name) values('HNRX');
            insert into artists(artist_name) values('Kurtz Amor');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Soy');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Konku');
            insert into artists(artist_name) values('Anonymous');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Birds');
            insert into artists(artist_name) values('Birds');
            insert into artists(artist_name) values('Kurtz Amor');
            insert into artists(artist_name) values('Opse');
            insert into artists(artist_name) values('SPEK');
            insert into artists(artist_name) values('Link');
            insert into artists(artist_name) values('Dash');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Jos*');
            insert into artists(artist_name) values('Slom');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Olé');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Runs!');
            insert into artists(artist_name) values('Jos*');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Stoul');
            insert into artists(artist_name) values('Rodin');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Dilen');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Betty');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Oase');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Cinda');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Tsyc');
            insert into artists(artist_name) values('Akbar');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Crisa');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Anderson');
            insert into artists(artist_name) values('Kurtz Amor');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('GLAM');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Jhon Douglas');
            insert into artists(artist_name) values('SPEK');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Black Sneaker');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Hazul Luzah');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Lust');
            insert into artists(artist_name) values('Theo Eifig');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Dirty Cop');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Hibashira');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('MONSTER');
            insert into artists(artist_name) values('Time');
            insert into artists(artist_name) values('I´m from Lisboa');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('David Walker');
            insert into artists(artist_name) values('Odeith');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Sphiza');
            insert into artists(artist_name) values('Creyz');
            insert into artists(artist_name) values('Conor Harrington');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('David Walker');
            insert into artists(artist_name) values('Tiago Marques');
            insert into artists(artist_name) values('Inês Madeira');
            insert into artists(artist_name) values('Bruno Canas');
            insert into artists(artist_name) values('±maismenos±');
            insert into artists(artist_name) values('Dirty Cop');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Dirty Cop');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('Chure Oner');
            insert into artists(artist_name) values('Time');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Hium');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('RAM');
            insert into artists(artist_name) values('Hibashira');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Fábio Santos');
            insert into artists(artist_name) values('José Fictício');
            insert into artists(artist_name) values('Rui Ventura');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Kebekua');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Youth One');
            insert into artists(artist_name) values('Miguel Noronha');
            insert into artists(artist_name) values('Christophe-Paul Sauvage');
            insert into artists(artist_name) values('Telmo Alcobia');
            insert into artists(artist_name) values('Ateme e Uhgo');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Recan');
            insert into artists(artist_name) values('André da Loba');
            insert into artists(artist_name) values('Alessandra Tassone');
            insert into artists(artist_name) values('Moami');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('Juan Pablo Zaramella');
            insert into artists(artist_name) values('Hibashira');
            insert into artists(artist_name) values('Teresa Robalo aka URSA');
            insert into artists(artist_name) values('Can Can Club');
            insert into artists(artist_name) values('Tania de Leon');
            insert into artists(artist_name) values('Dois Vês');
            insert into artists(artist_name) values('Bruno Casanova');
            insert into artists(artist_name) values('FLIX');
            insert into artists(artist_name) values('Can Can Club');
            insert into artists(artist_name) values('Gleo');
            insert into artists(artist_name) values('Steep');
            insert into artists(artist_name) values('FLIX');
            insert into artists(artist_name) values('Nuno Alecrim');
            insert into artists(artist_name) values('Eduardo Kobra');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('Godmess');
            insert into artists(artist_name) values('Guilherme Kramer');
            insert into artists(artist_name) values('Kruella d'Enfer');
            insert into artists(artist_name) values('LS');
            insert into artists(artist_name) values('Jhon Douglas');
            insert into artists(artist_name) values('Hazul Luzah');
            insert into artists(artist_name) values('Zesar Bahamonte');
            insert into artists(artist_name) values('Medianeras');
            insert into artists(artist_name) values('The Caver');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('Klit');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('Hibashira');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('Isa Silva');
            insert into artists(artist_name) values('San Spiga');
            insert into artists(artist_name) values('Francisco Camilo');
            insert into artists(artist_name) values('Tito Ferrara');
            insert into artists(artist_name) values('LS');
            insert into artists(artist_name) values('ARM Collective');
            insert into artists(artist_name) values('Trafic.asart');
            insert into artists(artist_name) values('PRAKTIS');
            insert into artists(artist_name) values('Shepard Fairey');
            insert into artists(artist_name) values('ALME CREW');
            insert into artists(artist_name) values('L7MATRIX &amp; SKRAN');
            insert into artists(artist_name) values('L7MATRIX &amp; SKRAN');
            insert into artists(artist_name) values('Obey (USA)');
            insert into artists(artist_name) values('Shepard Fairey');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Regg');
            insert into artists(artist_name) values('FLIX');
            insert into artists(artist_name) values('Mosaik');
            insert into artists(artist_name) values('Tamara Alves');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Felipe Pantone');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Zé');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('Tinta Crua');
            insert into artists(artist_name) values('Pantónio');
            insert into artists(artist_name) values('João Samina');
            insert into artists(artist_name) values('MAR');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('Stoul');
            insert into artists(artist_name) values('Dalaiama');
            insert into artists(artist_name) values('±maismenos±');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('Bloco de Esquerda');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('Aspen');
            insert into artists(artist_name) values('Dalaiama');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('Francisco Vidal');
            insert into artists(artist_name) values('DAMA');
            insert into artists(artist_name) values('2Hands');
            insert into artists(artist_name) values('WK INTERACT');
            insert into artists(artist_name) values('Add Fuel');
            insert into artists(artist_name) values('Nuno Alecrim');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('PichiAvo');
            insert into artists(artist_name) values('EIME');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('Mário Belém');
            insert into artists(artist_name) values('CAZE ARTE &amp; ALEX');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('CAZE ARTE &amp; ALEX');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Oze Arv');
            insert into artists(artist_name) values('Ener Konings');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('Nuno Saraiva');
            insert into artists(artist_name) values('ALEX SENNA');
            insert into artists(artist_name) values('LAMAS');
            insert into artists(artist_name) values('VERCESI');
            insert into artists(artist_name) values('KOZ ON');
            insert into artists(artist_name) values('Théo Vallier');
            insert into artists(artist_name) values('EXPLOR');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Théo Vallier');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('LS');
            insert into artists(artist_name) values('João Morais');
            insert into artists(artist_name) values('GRUPO OPNI');
            insert into artists(artist_name) values('LS');
            insert into artists(artist_name) values('Daco');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Bordalo II');
            insert into artists(artist_name) values('Godmess');
            insert into artists(artist_name) values('CHRISTIAN RUG');
            insert into artists(artist_name) values('THEO AGGAÏ');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('ORPHÃO');
            insert into artists(artist_name) values('Miguel Brum');
            insert into artists(artist_name) values('BIGOD');
            insert into artists(artist_name) values('RITA GRAÇA');
            insert into artists(artist_name) values('Styler');
            insert into artists(artist_name) values('RISCACOMOQUEHÁ');
            insert into artists(artist_name) values('RAPS');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('MANOEL JACK');
            insert into artists(artist_name) values('DIOGO CAMILO');
            insert into artists(artist_name) values('Smile');
            insert into artists(artist_name) values('Ôje');
            insert into artists(artist_name) values('J. de Montaigne');
            insert into artists(artist_name) values('MÁRCIO BAHIA');
            insert into artists(artist_name) values('GONÇALO MOREIRA');
            insert into artists(artist_name) values('OBSERV');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Utopia');
            insert into artists(artist_name) values('Styler');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('2CARRYON');
            insert into artists(artist_name) values('ANDRÉ NADA');
            insert into artists(artist_name) values('ROCIO MATOSAS');
            insert into artists(artist_name) values('ART' ODIDATA');
            insert into artists(artist_name) values('OPIEMME');
            insert into artists(artist_name) values('Francisco Camilo');
            insert into artists(artist_name) values('Autor desconhecido');
            insert into artists(artist_name) values('NINA VALKHOFF');
            insert into artists(artist_name) values('J. de Montaign &amp; Rezende');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('RAGS');
            insert into artists(artist_name) values('DARRY PERIER');
            insert into artists(artist_name) values('AIRBORNE MARK');
            insert into artists(artist_name) values('CAZE ARTE &amp; ALEX');
            insert into artists(artist_name) values('KARLEK OCHAVENTYR');
            insert into artists(artist_name) values('2UPLA');
            insert into artists(artist_name) values('TEOSON');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('J. de Montaigne');
            insert into artists(artist_name) values('ANDRÉ ACER');
            insert into artists(artist_name) values('Slap');
            insert into artists(artist_name) values('ANDRÉ ACER');
            insert into artists(artist_name) values('Guatê Mao');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Tina Tictone');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Lo Zer');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('SKRAN');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('DIRTY CUP');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Another');
            insert into artists(artist_name) values('André Fernades Trindade');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Raf');
            insert into artists(artist_name) values('Zana');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('Desconhecido');
            insert into artists(artist_name) values('TURNE DOG');
            insert into artists(artist_name) values('Vhils');
            insert into artists(artist_name) values('Mata One');
            insert into artists(artist_name) values('BRAIN PAINT CIRCLE');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('Hugo Lucas');
            insert into artists(artist_name) values('MÁRCIO BAHIA');
            insert into artists(artist_name) values('MÁRCIO BAHIA');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('Nomen');
            insert into artists(artist_name) values('Costah');
            insert into artists(artist_name) values('INSANOS');
            insert into artists(artist_name) values('INSANOS');
            insert into artists(artist_name) values('C.A.R.V.A.L.H.O');
            